services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: eco_collect_postgres_dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-waste_collection}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - eco_collect_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: eco_collect_redis_dev
    volumes:
      - redis_data:/data
    networks:
      - eco_collect_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eco_collect_backend_dev
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-airflow}@postgres:5432/${POSTGRES_DB:-waste_collection}
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - MAIL_SERVER=${MAIL_SERVER:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-465}
      - MAIL_USE_TLS=${MAIL_USE_TLS:-false}
      - MAIL_USE_SSL=${MAIL_USE_SSL:-true}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - OTP_EXPIRY=${OTP_EXPIRY:-300}
      - OTP_LENGTH=${OTP_LENGTH:-6}
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "8000:5000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/app/__pycache__
      - /app/app/routes/__pycache__
      - /app/app/utils/__pycache__
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - eco_collect_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: eco_collect_frontend_dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://backend:5000/api}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./eslint.config.js:/app/eslint.config.js
      - ./components.json:/app/components.json
      - node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - eco_collect_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  node_modules:
    driver: local

networks:
  eco_collect_network:
    driver: bridge

# For production, copy .env.example to .env and set all secrets/keys
# docker-compose --env-file .env up -d 